### PR TITLE
Minor additions for improved communication efficiency (test_86 branch)

### PR DESCRIPTION
**Pull request by Luxovious**
I have played around and tried to fullfill the request I made myself in issue https://github.com/RobTillaart/PCA9634/issues/18. Please check intensively, if my changes make sense. They seem to work when used with a single PCA9634. However, I was not able to test the communication with multiple PCA9634, yet. I therefore believe a merge with the test_86 branch would make sense, but a merge with the master-branch is still too early. I will try to test this soon.

### CODE REVIEW

**Comment by RobTillaart** [comment]
(Still groggy - severe cold)

@Luxovious 

At first (blurred) sight the code looks in the right direction in theory. There are some practical 2nd thoughts however.

#### return value
>    }
  return PCA9634_OK;  // <-- I am not sure if a check for error should be included here. I just added "return PCA9634_OK;", because my compiler told me that I need an uint8_t to return.
}

The return value is not that exiting for now. 

#### internal behavior wire class

A more problematic thing (to be investigated) is how the workflow will be.
The idea is to call **:writeN_noStop()** a few times, followed by a single **writeStop()**

That implies several **beginTransmission()** + **write()** calls after each other. 
followed by a single **endTransmission()** at the end.  ==> so not a balanced  begin-end 

Are multiple beginTransmissions allowed?  
As it sets the address it might be overwritten(?), causing data to go to the wrong device.

The **write()** call do not write actually if I recall correctly, the **endTransmission()** does 
(UNO, other platforms may differ)

As the internal buffer (I2C) is platform dependent (UNO ~32, ESP ~128 ?) the multiple writes might overflow on the smaller buffers. although 32 bytes is still quite a lot.

Think the proposed code works as it does not use multiple calls to **:writeN_noStop()**  yet. 

#### idea / solution?

Think you need to have a good look at the Wire interface.
There also exists  **endTransmission(bool sendstop)** although it not common used. It makes it possible to send the data without the STOP at the end. 
By adding **endTransmission(false)** call in the **:writeN_noStop()**  data is send without the stop as you want,

The **writeStop()** should have a **beginTransmission()** and a **endTransmission(true)** to complete it.

As far as my brain can oversee this solves the possible problems mentioned before.

Does this help?

**Review by RobTillaart — APPROVED** [review]

**Comment by Luxovious** [comment]
> Are multiple beginTransmissions allowed? As it sets the address it might be overwritten(?), causing data to go to the wrong device.

Yes, they are. As far as I understand the comments in the twi-library (on which the wire library builds on?), it is implemented. It is called "repeated start" and is essentially an address-only start. The code can be found here: [line 226 of twi.c](https://github.com/codebendercc/arduino-library-files/blob/master/libraries/Wire/utility/twi.c)

> The **write()** call do not write actually if I recall correctly, the **endTransmission()** does (UNO, other platforms may differ)

Are you sure? the code of the write() function seems to indicate differently: [line 183 of wire.cpp](https://github.com/esp8266/Arduino/blob/master/libraries/Wire/Wire.cpp)

> Think the proposed code works as it does not use multiple calls to **:writeN_noStop()** yet.

I am pretty sure I tested that. And it worked just as intended. Maybe I should double check sometime soon.

> #### idea / solution?
> Think you need to have a good look at the Wire interface. There also exists **endTransmission(bool sendstop)** although it not common used. It makes it possible to send the data without the STOP at the end. By adding **endTransmission(false)** call in the **:writeN_noStop()** data is send without the stop as you want,
> 
> The **writeStop()** should have a **beginTransmission()** and a **endTransmission(true)** to complete it.
> 
> As far as my brain can oversee this solves the possible problems mentioned before.
> 
> Does this help?

I don't know. I can somewhat read code (if it is well documented) but hardly write 😅

**Comment by RobTillaart** [comment]
There seems to be a conflict in PCA9634.h - I will look into it but time is limited (life is all about priorities)

**Comment by RobTillaart** [comment]
Seemed to be a minor one.

**Comment by Luxovious** [comment]
Hi Rob,
I consolidated my fork, as I have tested my code and I was not able to find issues with it. a few weeks back I took a look at the original wire.h and twi.h libraries. If I have not overlooked anything, my additions/suggestions should not cause any issues.

If you don't like the **:writeN_noStop()** or **writeStop()** functions, that is fine. I will use them in my own code nonetheless, as they work for me. However, I would like the other changes (including my fixes for the AllCall-addresses) to be pulled if possible. They don't really touch the core of your library and they are nice additions/correction which improve the usability for everyone.

**Comment by RobTillaart** [comment]
Will merge them today, I have other priorities (affecting build of all libraries) so I did not review them in detail. 
Coming time there will be another major upgrade for all workflows of all libraries. And I have planned to go through my archives to publish new libraries as there are a few dozen half baked that need "to grow up" or must be removed.

**Comment by RobTillaart** [comment]
@Luxovious 

This closes https://github.com/RobTillaart/PCA9634/issues/18  ?

**Pull request merged**
